version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - openssl req -new -x509 -nodes -utf8 -newkey rsa:2048 -keyout metadata.key -days 3600 -subj "/CN=$CN" -out metadata.crt;
      - /bin/bash -c 'secret=$(aws secretsmanager get-secret-value --secret-id "$METADATA_CERT_SECRET_ARN"); 
        if [ $? -gt 0 ] || [ $(echo $secret | jq -r .SecretString | awk '"'"'{print length}'"'"') -lt 2 ]; 
        then 
          echo Writing Certificate; 
          aws secretsmanager put-secret-value --secret-id "$METADATA_CERT_SECRET_ARN" --secret-string "$(cat metadata.crt)"; 
        else 
          echo Certificate Secret already contains a value; 
        fi'
      - /bin/bash -c 'secret=$(aws secretsmanager get-secret-value --secret-id "$PRIVATE_KEY_SECRET_ARN"); 
        if [ $? -gt 0 ] || [ $(echo $secret | jq -r .SecretString | awk '"'"'{print length}'"'"') -lt 2 ]; 
        then 
          echo Writing Private Key; 
          aws secretsmanager put-secret-value --secret-id "$PRIVATE_KEY_SECRET_ARN" --secret-string "$(cat metadata.key)"; 
        else 
          echo Private Key Secret already contains a value;           
        fi'   
