attributes:
  #AWS Attributes
  role: 
    saml: [RoleEntitlement]
  rolesessionname:
    saml: [RoleSessionName]
  sessionduration:
    saml: [SessionDuration]
  transitivetagkeys:
    saml: [TransitiveTagKeys]